In [1]:
import pandas as pd
from matplotlib import pyplot as plt 
import numpy as np 
%matplotlib inline
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# // we will build a deep learning model to predict the attrition and use precision to measure performance of our model //

df = pd.read_csv("C:\\Users\\HP\\Downloads\\customer_attrition_train.csv")
df.sample(50)
print(df)

                        ID     sex Aged Married TotalDependents  ServiceSpan  \
0     B60LHTZLLPFU4IULNPUF  Female   No      No             Yes           48
1     1RUJ7ONYZHYTWKOKO1SD    Male   No     Yes              No           45
2     DZ9EEOQWSN0MYCBUPAM5    Male  Yes     Yes              No           59
3     YZ43L1UQUQACTL1PXXZG    Male   No      No              No           14
4     6P28152QGF60PDLSCB9M  Female   No     Yes             Yes           25
...                    ...     ...  ...     ...             ...          ...
6333  Y7U717HO87PCW6XXIQA1  Female  Yes      No              No            3
6334  NGY3WOQ0OT1P4RHAR0PT  Female  Yes      No              No           -1
6335  ZBBW7H8AYLZJ2HK5TBBJ    Male   No      No             Yes           18
6336  BUE75NSSLT2S2URTKZRN    Male   No     Yes              No           46
6337  IRFAYIAO820RIX2GUFFF  Female   No      No              No           60

     MobileService            4GService CyberProtection HardwareSupport  \
0              Yes       Wifi Broadband              No             Yes
1              Yes       Wifi Broadband              No              No
2              Yes       Wifi Broadband             Yes              No
3              Yes       Wifi Broadband              No              No
4              Yes       Wifi Broadband              No             Yes
...            ...                  ...             ...             ...
6333           Yes       Wifi Broadband              No             Yes
6334           Yes  Satellite Broadband              No              No
6335           Yes                   No              No              No
6336           Yes                   No              No              No
6337           Yes  Satellite Broadband              No              No

     TechnicalAssistance FilmSubscription SettlementProcess  QuarterlyPayment  \
0                    Yes               No             Check         96.259802
1                     No              Yes              Bank         18.876470
2                    Yes               No              Card        106.016057
3                     No               No             Check         80.108839
4                     No              Yes             Check         51.529773
...                  ...              ...               ...               ...
6333                  No              Yes              Card        100.391595
6334                  No              Yes              Bank         44.782165
6335                  No               No        Electronic         35.941713
6336                  No              Yes              Card         94.762984
6337                  No               No              Bank         94.337343

      GrandPayment CustomerAttrition
0      4628.129119               Yes
1       922.085998                No
2      6205.891129               Yes
3      1248.655391                No
4      1285.321277                No
...            ...               ...
6333    441.914530               Yes
6334     45.308180                No
6335    552.181341               Yes
6336   4563.812326                No
6337   5756.542013                No

[6338 rows x 16 columns]

In [2]:
df.drop('ID',axis= 'columns',inplace = True)
print(df)
print(df.dtypes)

         sex Aged Married TotalDependents  ServiceSpan MobileService  \
0     Female   No      No             Yes           48           Yes
1       Male   No     Yes              No           45           Yes
2       Male  Yes     Yes              No           59           Yes
3       Male   No      No              No           14           Yes
4     Female   No     Yes             Yes           25           Yes
...      ...  ...     ...             ...          ...           ...
6333  Female  Yes      No              No            3           Yes
6334  Female  Yes      No              No           -1           Yes
6335    Male   No      No             Yes           18           Yes
6336    Male   No     Yes              No           46           Yes
6337  Female   No      No              No           60           Yes

                4GService CyberProtection HardwareSupport TechnicalAssistance  \
0          Wifi Broadband              No             Yes                 Yes
1          Wifi Broadband              No              No                  No
2          Wifi Broadband             Yes              No                 Yes
3          Wifi Broadband              No              No                  No
4          Wifi Broadband              No             Yes                  No
...                   ...             ...             ...                 ...
6333       Wifi Broadband              No             Yes                  No
6334  Satellite Broadband              No              No                  No
6335                   No              No              No                  No
6336                   No              No              No                  No
6337  Satellite Broadband              No              No                  No

     FilmSubscription SettlementProcess  QuarterlyPayment  GrandPayment  \
0                  No             Check         96.259802   4628.129119
1                 Yes              Bank         18.876470    922.085998
2                  No              Card        106.016057   6205.891129
3                  No             Check         80.108839   1248.655391
4                 Yes             Check         51.529773   1285.321277
...               ...               ...               ...           ...
6333              Yes              Card        100.391595    441.914530
6334              Yes              Bank         44.782165     45.308180
6335               No        Electronic         35.941713    552.181341
6336              Yes              Card         94.762984   4563.812326
6337               No              Bank         94.337343   5756.542013

     CustomerAttrition
0                  Yes
1                   No
2                  Yes
3                   No
4                   No
...                ...
6333               Yes
6334                No
6335               Yes
6336                No
6337                No

[6338 rows x 15 columns]
sex                     object
Aged                    object
Married                 object
TotalDependents         object
ServiceSpan              int64
MobileService           object
4GService               object
CyberProtection         object
HardwareSupport         object
TechnicalAssistance     object
FilmSubscription        object
SettlementProcess       object
QuarterlyPayment       float64
GrandPayment           float64
CustomerAttrition       object
dtype: object

In [3]:
print(df.GrandPayment.values)
pd.to_numeric(df.GrandPayment , errors='coerce').isnull

[4628.129119   922.0859985 6205.891129  ...  552.1813408 4563.812326
 5756.542013 ]

<bound method Series.isnull of 0       4628.129119
1        922.085998
2       6205.891129
3       1248.655391
4       1285.321277
           ...
6333     441.914530
6334      45.308180
6335     552.181341
6336    4563.812326
6337    5756.542013
Name: GrandPayment, Length: 6338, dtype: float64>

In [4]:
def print_unique_col_values(df):
    for column in df :
        if df [column].dtypes=='object':
            print (f'{column}:{df[column].unique()}')
print_unique_col_values(df)

sex:['Female' 'Male']
Aged:['No' 'Yes']
Married:['No' 'Yes']
TotalDependents:['Yes' 'No']
MobileService:['Yes' 'No']
4GService:['Wifi Broadband' 'Satellite Broadband' 'No']
CyberProtection:['No' 'Yes']
HardwareSupport:['Yes' 'No']
TechnicalAssistance:['Yes' 'No']
FilmSubscription:['No' 'Yes']
SettlementProcess:['Check' 'Bank' 'Card' 'Electronic']
CustomerAttrition:['Yes' 'No']

In [5]:
columnys = ['Aged', 'Married', 'TotalDependents','MobileService','CyberProtection','HardwareSupport','TechnicalAssistance','FilmSubscription','CustomerAttrition']

for items in columnys:
    df[items].replace({'No':0,'Yes':1}, inplace = True)
# df['TotalDependents'].replace({'No':0,'Yes':1},inplace = True)
df['sex'].replace({'Female':0,'Male':1}, inplace=True)
df = pd.get_dummies(data=df , columns = ['4GService','SettlementProcess'])

In [6]:
for col in df:
    print(f'{col}:{df[col].unique()}')
df

sex:[0 1]
Aged:[0 1]
Married:[0 1]
TotalDependents:[1 0]
ServiceSpan:[48 45 59 14 25 27 53  0  1 46 67 24 61 54  9 30 18  5 64  3 41 40 31 21
 15  6 69 72 33 71  2 36  8 37 34 28 -1 60 22 68 11 39 58 10 50  4 44 49
 38 55 51 16 65 13 26 19 57 70 73 42 35 62 23 56 47 63 32 29  7 20 43 12
 52 17 66 -2]
MobileService:[1 0]
CyberProtection:[0 1]
HardwareSupport:[1 0]
TechnicalAssistance:[1 0]
FilmSubscription:[0 1]
QuarterlyPayment:[ 96.25980197  18.87647016 106.0160571  ...  35.94171339  94.76298428
  94.3373432 ]
GrandPayment:[4628.129119   922.0859985 6205.891129  ...  552.1813408 4563.812326
 5756.542013 ]
CustomerAttrition:[1 0]
4GService_No:[0 1]
4GService_Satellite Broadband:[0 1]
4GService_Wifi Broadband:[1 0]
SettlementProcess_Bank:[0 1]
SettlementProcess_Card:[0 1]
SettlementProcess_Check:[1 0]
SettlementProcess_Electronic:[0 1]

,sex,Aged,Married,TotalDependents,ServiceSpan,MobileService,CyberProtection,HardwareSupport,TechnicalAssistance,FilmSubscription,QuarterlyPayment,GrandPayment,CustomerAttrition,4GService_No,4GService_Satellite Broadband,4GService_Wifi Broadband,SettlementProcess_Bank,SettlementProcess_Card,SettlementProcess_Check,SettlementProcess_Electronic
0,0,0,0,1,48,1,0,1,1,0,96.259802,4628.129119,1,0,0,1,0,0,1,0
1,1,0,1,0,45,1,0,0,0,1,18.876470,922.085998,0,0,0,1,1,0,0,0
2,1,1,1,0,59,1,1,0,1,0,106.016057,6205.891129,1,0,0,1,0,1,0,0
3,1,0,0,0,14,1,0,0,0,0,80.108839,1248.655391,0,0,0,1,0,0,1,0
4,0,0,1,1,25,1,0,1,0,1,51.529773,1285.321277,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6333,0,1,0,0,3,1,0,1,0,1,100.391595,441.914530,1,0,0,1,0,1,0,0
6334,0,1,0,0,-1,1,0,0,0,1,44.782165,45.308180,0,0,1,0,1,0,0,0
6335,1,0,0,1,18,1,0,0,0,0,35.941713,552.181341,1,1,0,0,0,0,0,1
6336,1,0,1,0,46,1,0,0,0,1,94.762984,4563.812326,0,1,0,0,0,1,0,0
6337,0,0,0,0,60,1,0,0,0,0,94.337343,5756.542013,0,0,1,0,1,0,0,0

In [7]:
df.columns

Index(['sex', 'Aged', 'Married', 'TotalDependents', 'ServiceSpan',
       'MobileService', 'CyberProtection', 'HardwareSupport',
       'TechnicalAssistance', 'FilmSubscription', 'QuarterlyPayment',
       'GrandPayment', 'CustomerAttrition', '4GService_No',
       '4GService_Satellite Broadband', '4GService_Wifi Broadband',
       'SettlementProcess_Bank', 'SettlementProcess_Card',
       'SettlementProcess_Check', 'SettlementProcess_Electronic'],
      dtype='object')

In [8]:
df.dtypes

sex                                int64
Aged                               int64
Married                            int64
TotalDependents                    int64
ServiceSpan                        int64
MobileService                      int64
CyberProtection                    int64
HardwareSupport                    int64
TechnicalAssistance                int64
FilmSubscription                   int64
QuarterlyPayment                 float64
GrandPayment                     float64
CustomerAttrition                  int64
4GService_No                       uint8
4GService_Satellite Broadband      uint8
4GService_Wifi Broadband           uint8
SettlementProcess_Bank             uint8
SettlementProcess_Card             uint8
SettlementProcess_Check            uint8
SettlementProcess_Electronic       uint8
dtype: object

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
cols_to_scale = ['ServiceSpan', 'QuarterlyPayment','GrandPayment']
df[cols_to_scale]=scaler.fit_transform(df[cols_to_scale])

In [10]:
for col in df:
    print(f'{col}:{df[col].unique()}')

sex:[0 1]
Aged:[0 1]
Married:[0 1]
TotalDependents:[1 0]
ServiceSpan:[0.66666667 0.62666667 0.81333333 0.21333333 0.36       0.38666667
 0.73333333 0.02666667 0.04       0.64       0.92       0.34666667
 0.84       0.74666667 0.14666667 0.42666667 0.26666667 0.09333333
 0.88       0.06666667 0.57333333 0.56       0.44       0.30666667
 0.22666667 0.10666667 0.94666667 0.98666667 0.46666667 0.97333333
 0.05333333 0.50666667 0.13333333 0.52       0.48       0.4
 0.01333333 0.82666667 0.32       0.93333333 0.17333333 0.54666667
 0.8        0.16       0.69333333 0.08       0.61333333 0.68
 0.53333333 0.76       0.70666667 0.24       0.89333333 0.2
 0.37333333 0.28       0.78666667 0.96       1.         0.58666667
 0.49333333 0.85333333 0.33333333 0.77333333 0.65333333 0.86666667
 0.45333333 0.41333333 0.12       0.29333333 0.6        0.18666667
 0.72       0.25333333 0.90666667 0.        ]
MobileService:[1 0]
CyberProtection:[0 1]
HardwareSupport:[1 0]
TechnicalAssistance:[1 0]
FilmSubscription:[0 1]
QuarterlyPayment:[0.76943351 0.02288707 0.86355581 ... 0.18752196 0.75499314 0.75088682]
GrandPayment:[0.53195734 0.10447924 0.71394625 ... 0.06181213 0.52453864 0.66211552]
CustomerAttrition:[1 0]
4GService_No:[0 1]
4GService_Satellite Broadband:[0 1]
4GService_Wifi Broadband:[1 0]
SettlementProcess_Bank:[0 1]
SettlementProcess_Card:[0 1]
SettlementProcess_Check:[1 0]
SettlementProcess_Electronic:[0 1]

In [11]:
x=df.drop('CustomerAttrition',axis='columns')
y=df['CustomerAttrition']

In [71]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test = train_test_split (x,y,test_size=0.0378,random_state=8)
#0.3483
x_train[:25]
len(x_train.columns)

19

In [13]:
x_train.shape

(4130, 19)

In [14]:
x_test.shape

(2208, 19)

In [33]:
import tensorflow as tf
from tensorflow import keras

model=keras.Sequential([
    keras.layers.Dense(16,input_shape=(19,),activation='relu'),
    keras.layers.Dense(12 , activation = 'relu'),
    keras.layers.Dense(1,activation='sigmoid')
]
)
# model.summary()
model.compile(optimizer='adam',
             loss = 'binary_crossentropy',
             metrics = ['accuracy'])
model.fit(x_train,y_train, epochs=20, batch_size=150, shuffle=True)

# model.predict()

Epoch 1/20
28/28 [==============================] - 1s 3ms/step - loss: nan - accuracy: 0.7356
Epoch 2/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7305
Epoch 3/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7325
Epoch 4/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7295
Epoch 5/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7293
Epoch 6/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7268
Epoch 7/20
28/28 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7440
Epoch 8/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7310
Epoch 9/20
28/28 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7323
Epoch 10/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7302
Epoch 11/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7292
Epoch 12/20
28/28 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7457
Epoch 13/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7300
Epoch 14/20
28/28 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.7436
Epoch 15/20
28/28 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7254
Epoch 16/20
28/28 [==============================] - 0s 3ms/step - loss: nan - accuracy: 0.7264
Epoch 17/20
28/28 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.7407
Epoch 18/20
28/28 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.7277
Epoch 19/20
28/28 [==============================] - 0s 4ms/step - loss: nan - accuracy: 0.7306
Epoch 20/20
28/28 [==============================] - 0s 2ms/step - loss: nan - accuracy: 0.7319

In [72]:
model.evaluate(x_test,y_test)

8/8 [==============================] - 0s 5ms/step - loss: nan - accuracy: 0.8042

[nan, 0.8041666746139526]

In [28]:
model.predict(x_test)

array([[nan],
       [nan],
       [nan],
       ...,
       [nan],
       [nan],
       [nan]], dtype=float32)